///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
const String _jsonKeySignUpUser = 'user';
const String _jsonKeySignUpToken = 'token';
const String _jsonKeySignUpUserId = 'id';
const String _jsonKeySignUpUserPassword = 'password';
const String _jsonKeySignUpUserLastLogin = 'last_login';
const String _jsonKeySignUpUserIsSuperuser = 'is_superuser';
const String _jsonKeySignUpUserUsername = 'username';
const String _jsonKeySignUpUserFirstName = 'first_name';
const String _jsonKeySignUpUserLastName = 'last_name';
const String _jsonKeySignUpUserEmail = 'email';
const String _jsonKeySignUpUserIsStaff = 'is_staff';
const String _jsonKeySignUpUserIsActive = 'is_active';
const String _jsonKeySignUpUserDateJoined = 'date_joined';
const String _jsonKeySignUpUserGroups = 'groups';
const String _jsonKeySignUpUserUserPermissions = 'user_permissions';
class SignUpUser {
/*
{
  "id": 7,
  "password": "pbkdf2_sha256$320000$LSt1YlSozkllyDC2jBp3B7$li1bbREY13Z7IJo3mZW/x4sjt7mC2EQC5UjSxGcG7WU=",
  "last_login": null,
  "is_superuser": false,
  "username": "user",
  "first_name": "user",
  "last_name": "user",
  "email": "user@user.com",
  "is_staff": false,
  "is_active": true,
  "date_joined": "2022-03-06T04:07:38.999133Z",
  "groups": [
    null
  ],
  "user_permissions": [
    null
  ]
}
*/

  int? id;
  String? password;
  String? lastLogin;
  bool? isSuperuser;
  String? username;
  String? firstName;
  String? lastName;
  String? email;
  bool? isStaff;
  bool? isActive;
  String? dateJoined;
  List<SignUpUser?>? groups;
  List<SignUpUser>? userPermissions;
  Map<String, dynamic> __origJson = {};

  SignUpUser({
    this.id,
    this.password,
    this.lastLogin,
    this.isSuperuser,
    this.username,
    this.firstName,
    this.lastName,
    this.email,
    this.isStaff,
    this.isActive,
    this.dateJoined,
    this.groups,
    this.userPermissions,
  });
  SignUpUser.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = int.tryParse(json[_jsonKeySignUpUserId]?.toString() ?? '');
    password = json[_jsonKeySignUpUserPassword]?.toString();
    lastLogin = json[_jsonKeySignUpUserLastLogin]?.toString();
    isSuperuser = json[_jsonKeySignUpUserIsSuperuser];
    username = json[_jsonKeySignUpUserUsername]?.toString();
    firstName = json[_jsonKeySignUpUserFirstName]?.toString();
    lastName = json[_jsonKeySignUpUserLastName]?.toString();
    email = json[_jsonKeySignUpUserEmail]?.toString();
    isStaff = json[_jsonKeySignUpUserIsStaff];
    isActive = json[_jsonKeySignUpUserIsActive];
    dateJoined = json[_jsonKeySignUpUserDateJoined]?.toString();
    }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data[_jsonKeySignUpUserId] = id;
    data[_jsonKeySignUpUserPassword] = password;
    data[_jsonKeySignUpUserLastLogin] = lastLogin;
    data[_jsonKeySignUpUserIsSuperuser] = isSuperuser;
    data[_jsonKeySignUpUserUsername] = username;
    data[_jsonKeySignUpUserFirstName] = firstName;
    data[_jsonKeySignUpUserLastName] = lastName;
    data[_jsonKeySignUpUserEmail] = email;
    data[_jsonKeySignUpUserIsStaff] = isStaff;
    data[_jsonKeySignUpUserIsActive] = isActive;
    data[_jsonKeySignUpUserDateJoined] = dateJoined;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}

class SignUp {
/*
{
  "user": {
    "id": 7,
    "password": "pbkdf2_sha256$320000$LSt1YlSozkllyDC2jBp3B7$li1bbREY13Z7IJo3mZW/x4sjt7mC2EQC5UjSxGcG7WU=",
    "last_login": null,
    "is_superuser": false,
    "username": "user",
    "first_name": "user",
    "last_name": "user",
    "email": "user@user.com",
    "is_staff": false,
    "is_active": true,
    "date_joined": "2022-03-06T04:07:38.999133Z",
    "groups": [
      null
    ],
    "user_permissions": [
      null
    ]
  },
  "token": "694316293e565c4119d4b3a39d0a92c606689a010990de75ab9842ee0117ba1c"
}
*/

  SignUpUser? user;
  String? token;
  Map<String, dynamic> __origJson = {};

  SignUp({
    this.user,
    this.token,
  });
  SignUp.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    user = (json[_jsonKeySignUpUser] != null && (json[_jsonKeySignUpUser] is Map)) ? SignUpUser.fromJson(json[_jsonKeySignUpUser]) : null;
    token = json[_jsonKeySignUpToken]?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data[_jsonKeySignUpUser] = user!.toJson();
    }
    data[_jsonKeySignUpToken] = token;
    return data;
  }
  Map<String, dynamic> origJson() => __origJson;
}
